#! /usr/bin/env python


"""
Originally from http://blog.sethroberts.net/2012/07/04/magic-dots-quasi-reinforcement-helps-get-things-done/
"""

import time
import datetime
import subprocess
import os
try:
    from pync import Notifier
except ImportError:
    print "********************************************************************"
    print "For Growl style notifications, install:"
    print "* terminal-notifier - https://github.com/alloy/terminal-notifier"
    print "* pync - https://pypi.python.org/pypi/pync"
    print "********************************************************************"


def main():
    print "Starting Magic Dots timer"
    dots = 0
    boxes = 0
    while True:
        time.sleep(60*6) #wait 6 minutes
        dots += 1
        if dots % 10 == 0:
            boxes += 1
            msg = ". {0} dots so far, and {1} boxes!  Good work!".format(dots, boxes)
        else:
            msg = ". {0} dots and counting -- Keep Going!".format(dots)
        print datetime.datetime.now(), msg
        subprocess.call(["say", "dot"])
        try:
            Notifier.notify(msg, group=os.getpid(), title="Magic Dots")
        except NameError:
            # pync and terminal-notifier must not be installed.
            pass


if __name__ == "__main__":
    main()
